# Generated by Django 3.2.6 on 2021-10-20 12:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField()),
                ('time_of_appointment', models.TimeField(choices=[(datetime.time(8, 0), '08:00 AM'), (datetime.time(9, 0), '09:00 AM'), (datetime.time(10, 0), '10:00 AM'), (datetime.time(11, 0), '11:00 AM'), (datetime.time(1, 0), '01:00 PM'), (datetime.time(2, 0), '02:00 PM'), (datetime.time(3, 0), '03:00 PM'), (datetime.time(4, 0), '04:00 PM'), (datetime.time(5, 0), '05:00 PM')])),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Expired', 'Expired'), ('Ongoing', 'Ongoing')], max_length=10)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, default='', max_length=20)),
                ('email_address', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('street', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(blank=True, default='', max_length=50)),
                ('zip_code', models.IntegerField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('last_name', 'first_name', 'middle_name'), ('street', 'city', 'zip_code', 'province')},
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, default='', max_length=20)),
                ('email_address', models.EmailField(max_length=50, unique=True)),
                ('contact_number', models.CharField(max_length=20, unique=True)),
                ('years_of_service', models.IntegerField()),
            ],
            options={
                'unique_together': {('last_name', 'first_name', 'middle_name')},
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.dentist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedures',
            field=models.ManyToManyField(to='myapp.Procedure'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date_of_appointment', 'time_of_appointment')},
        ),
    ]
